server: 
  port: 8888
spring: 
  mvc: 
    view: 
      prefix: /
      suffix: .html
common: 
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.225:1521:orcl
    username: 
    password:
  swagger:
    default-api-param-type: query
    title: title
    description: description
    version: version